name: Compile

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Environments
        run: |
          echo "SM_VERSION=1.10" >> $GITHUB_ENV
      
      - name: Install
        run: |
          bash scripts/install.sh
      
      - name: Compile
        run: |
          cd build/addons/sourcemod/scripting
          ./spcomp -E textstore.sp -o ../plugins/textstore.smx
          ./spcomp -E textstore_defaults.sp -o ../plugins/textstore_defaults.smx
          ./spcomp -E textstore_generic.sp -o ../plugins/textstore_generic.smx
          ./spcomp -E textstore_sqlite.sp -o ../plugins/textstore_sqlite.smx
          ./spcomp -E textstore_tf2.sp -o ../plugins/textstore_tf2.smx
