name: Package

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Environments
        run: |
          echo ::set-env name=SM_VERSION::1.10
      
      - name: Install
        run: |
          bash scripts/install.sh
      
      - name: Set Version
        run: |
          DATE=$(date "+%y%j%H%M")
      
      - name: Compile
        run: |
          cd build/addons/sourcemod/scripting
          ./spcomp batstore.sp -o ../plugins/batstore.smx
          ./spcomp batstore_defaults.sp -o ../plugins/batstore_defaults.smx
          ./spcomp batstore_generic.sp -o ../plugins/batstore_generic.smx
          ./spcomp batstore_tf2.sp -o ../plugins/batstore_tf2.smx
      
      - name: Package
        run: |
          bash scripts/package.sh
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: Bat-Store-$((DATE))
          path: ./build/package
