name: Package

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Environments
        run: |
          echo ::set-env name=SM_VERSION::1.10
      
      - name: Install
        run: |
          bash scripts/install.sh
      
      - name: Set Version
        run: |
          bash scripts/date.sh
      
      - name: Compile
        run: |
          cd build/addons/sourcemod/scripting
          ./spcomp textstore.sp -o ../plugins/textstore.smx
          ./spcomp textstore_defaults.sp -o ../plugins/textstore_defaults.smx
          ./spcomp textstore_generic.sp -o ../plugins/textstore_generic.smx
          ./spcomp textstore_tf2.sp -o ../plugins/textstore_tf2.smx
      
      - name: Package
        run: |
          bash scripts/package.sh
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: Bat-Store-${{env.DATE_VERSION}}
          path: ./build/package
